export { default as alegria } from './alegria.jpg';
export { default as Alegria } from './Alegria.png';
export { default as arrow } from './arrow.svg';
export { default as close } from './close.svg';
export { default as code } from './code.svg';
export { default as compartir } from './compartir.jpg';
export { default as computer } from './computer.jpg';
export { default as comunidad } from './comunidad.jpg';
export { default as css } from './css.jpg';
export { default as face } from './face.jpg';
export { default as face2 } from './face2.jpg';
export { default as face3 } from './face3.jpg';
export { default as face4 } from './face4.jpg';
export { default as facebook } from './facebook.svg';
export { default as favicon } from './favicon.png';
export { default as fondoLandingPageNaranja } from './fondo landing page naranja.png';
export { default as fondoLandingPageVerde } from './fondo landing page verde.png';
export { default as fondoPrincipal } from './fondo principal.png';
export { default as Imagotipo_MC } from './Imagotipo_MC.png';
export { default as Impresion } from './Impresión.png';
export { default as ira } from './ira.jpg';
export { default as Ira } from './Ira.png';
export { default as Isotipo_MC } from './Isotipo MC.png';
export { default as istockphoto } from './istockphoto-592020710-1024x1024.jpg';
export { default as leftarrow } from './leftarrow.svg';
export { default as Logotipo_MC } from './Logotipo MC.png';
export { default as macbook } from './macbook.png';
export { default as menu } from './menu.svg';
export { default as paint } from './paint.svg';
export { default as rightarrow } from './rightarrow.svg';
export { default as shapes } from './shapes.svg';
export { default as sorpresa } from './sorpresa.jpg';
export { default as tristeza } from './tristeza.jpg';
export { default as Tristeza } from './Tristeza.png';
export { default as twitter } from './twitter.svg';
export { default as vibrar } from './vibrar.png';
export { default as vibrarExtra } from './vibrar.png.jpg';
export { default as youtube } from './youtube.svg';